CREATE SEQUENCE HIBERNATE_SEQUENCE
  START WITH   0
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SCHEMA FRAMEWORK_DEMO AUTHORIZATION sa;

CREATE TABLE FRAMEWORK_DEMO.SHARED_RESPONSE_CACHE
(
  ID      BIGINT NOT NULL,
  UUID    CHAR(36),
  HEADERS VARCHAR(512),
  BODY    CLOB,
  PRIMARY KEY (ID)
);

CREATE TABLE FRAMEWORK_DEMO.USER
(
  ID         BIGINT NOT NULL,
  USER_NAME  VARCHAR(32),
  FIRST_NAME VARCHAR(64),
  LAST_NAME  VARCHAR(64),
  PASSWORD   CHAR(64),
  PRIMARY KEY (ID),
  CONSTRAINT AK_USER_NAME UNIQUE (USER_NAME)
)